Create SECURITY.md
az-digital/template pull request #3
Opened 2024-01-24 21:16 UTC by ejsamboy

## Description
Add security policy to template repo

Closes #1

2024-01-25 16:09 UTC, trackleft submitted a review, later dismissed

2024-01-26 16:07 UTC, trackleft approved these changes

2024-01-26 16:20 UTC, trackleft requested changes

2024-01-26 16:20 UTC, trackleft commented on .github/SECURITY.md
> +>> Automating code scanning and integrating it into your development process can help catch vulnerabilities early on and prevent security issues from becoming more serious down the line.
I'm not sure about this last part

2024-01-26 21:21 UTC, ejsamboy commented on .github/SECURITY.md
> +>> Automating code scanning and integrating it into your development process can help catch vulnerabilities early on and prevent security issues from becoming more serious down the line.
I will go ahead and remove everything after line 34

2024-01-26 23:58 UTC, bberndt-uaz commented on .github/SECURITY.md
> +>> To require MFA,  select Your Profile Photo → Your Organizations→ Settings → Security→Authentication Security. You can see all the details here.
```suggestion
For this reason, requiring Multi-Factor Authentication (MFA) for all your GitHub organizations is critical.
> MFA should be enforced for every GitHub user in your organizations.
>> To require MFA, select Your Profile Photo → Your Organizations → Settings → Security → Authentication Security. For more details, see the [GitHub documentation](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/requiring-two-factor-authentication-in-your-organization).
```

2024-01-30 16:47 UTC, bberndt-uaz approved these changes

2024-01-31 17:45 UTC, joeparsons approved these changes

2024-01-31 17:45 UTC, trackleft approved these changes

2024-01-31 17:45 UTC, tadean approved these changes

2024-01-31 17:46 UTC, merged